# shellcheck shell=bash
# Build the ISOs the VM tests need. Sourced, never executed.
#
#   the stock NixOS minimal installer ISO, downloaded once and cached
#   a repack of it whose default boot entry has a serial console, which is the
#     only way an unattended run can see the installer at all
#   repo.iso, this repository plus a test unique.nix, so the guest gets the
#     installer without needing 9p, a network share, or a git remote
#
# Everything lands in ASSET_CACHE so a second run of the suite does no network
# I/O at all.

ASSET_CACHE=${ASSET_CACHE:-$HOME/.cache/nixos-installer-vm}

# Matches the repo's stateVersion. The installer reads the real value out of
# nixos-version at install time; this only picks which ISO we download.
NIXOS_CHANNEL=${NIXOS_CHANNEL:-nixos-25.05}
ISO_URL="https://channels.nixos.org/$NIXOS_CHANNEL/latest-nixos-minimal-x86_64-linux.iso"
ISO_PATH="$ASSET_CACHE/nixos-minimal-${NIXOS_CHANNEL#nixos-}-x86_64.iso"

# The guest logs in as root on the serial console with no password, so this
# hostId is the only identity that matters. It must be 8 hex digits or
# install-me.sh refuses to run.
TEST_HOSTID=${TEST_HOSTID:-deadbe01}
TEST_HOSTNAME=${TEST_HOSTNAME:-vmtest-box}

fetch_iso () {
    mkdir -p "$ASSET_CACHE"
    if [[ -s $ISO_PATH ]]; then echo "$ISO_PATH"; return 0; fi
    curl -sSL --retry 3 -o "$ISO_PATH.part" "$ISO_URL" || return 1
    mv "$ISO_PATH.part" "$ISO_PATH"
    echo "$ISO_PATH"
}


# The per-machine file the installed system gets. Two things in here exist only
# for the tests:
#
#   - a serial console, so one expect harness can drive both the installer and
#     the installed system without SSH, a guest agent, or guest networking
#   - autologin, so reaching a root shell is the boot assertion
#
# Everything else is deliberately plain: the point is to exercise the real
# configuration.nix and disk-layout.nix, not a special test config.
write_test_unique_nix () { # write_test_unique_nix PATH
    cat > "$1" <<EOF
# Generated by tests/vm-boot.sh. Not for real machines: it autologs root in on
# the serial console.
{ config, pkgs, ... }:

{
  networking.hostName = "$TEST_HOSTNAME";
  networking.hostId = "$TEST_HOSTID";

  # Console on ttyS0 so the host can drive the guest over a TCP serial port.
  boot.kernelParams = [ "console=tty0" "console=ttyS0,115200n8" ];

  # GRUB itself talks to the same port, so a boot that dies in the bootloader
  # is visible to the test instead of just timing out.
  boot.loader.grub.extraConfig = ''
    serial --unit=0 --speed=115200
    terminal_input serial console
    terminal_output serial console
  '';

  systemd.services."serial-getty@ttyS0".enable = true;
  services.getty.autologinUser = "root";

  # A booted machine must not sit waiting for DHCP on a NIC the test does not
  # use; that turns a pass into a timeout.
  networking.useDHCP = false;
  systemd.services.NetworkManager-wait-online.enable = false;

  # Documentation is the single most expensive thing in this closure and the
  # least relevant to what is being tested. The NixOS manual and the man cache
  # are not in the binary cache -- they are generated per configuration -- so
  # under TCG emulation they are built from source and dominate the run. None
  # of it affects partitioning, the pool, the bootloader or the boot.
  documentation.nixos.enable = false;
  documentation.man.generateCaches = false;

  # Two boot-time time sinks that have nothing to do with these assertions.
  # timesyncd blocks for 90 guest-seconds waiting for a network clock, and the
  # scrub timer can start a scrub that saturates an emulated CPU -- on a guest
  # already running ~50x slower than wall clock, both are very expensive.
  services.timesyncd.enable = false;
  services.zfs.autoScrub.enable = false;

  # Docker is a large part of this closure and delays every boot ("A start job
  # is running for Docker Application Container Engine"), while this suite
  # asserts nothing about it: it drives install-me.sh with the data pool
  # skipped, so there is no data-root for docker to wait on. The docker/ZFS
  # wiring in configuration.nix is covered by tests/nix-eval.sh instead.
  virtualisation.docker.enable = false;

  # If something does have to be built in the guest, let it use every vCPU
  # rather than nix's default of one job.
  nix.settings.max-jobs = "auto";
  nix.settings.cores = 0;
}
EOF
}

# Rebuild the installer ISO so its *default* boot entry talks to the serial
# port, and so GRUB itself accepts serial input.
#
# This is the only reliable way in, and it is worth being explicit about why,
# because two more obvious approaches were tried and do not work:
#
#   1. QEMU direct kernel boot (-kernel/-initrd/-append). UTM stores extra
#      QEMU arguments as a flat string array and splits every entry on
#      whitespace, so a multi-word -append value arrives as several arguments
#      and QEMU treats the tail as disk images. Plain, double-quoted and
#      backslash-escaped forms all fail identically.
#   2. Driving the ISO's own bootloader over the serial console. OVMF does
#      mirror its output to serial and the GRUB menu is perfectly readable
#      there, but GRUB never acts on serial *input*: keystrokes are echoed,
#      the countdown still expires, and the default (non-serial) entry boots.
#
# Patching the ISO sidesteps both. `-boot_image any replay` copies the El
# Torito boot setup verbatim, so the result stays bootable in both BIOS and
# UEFI mode; only the two config files change.
repack_iso_for_serial () { # repack_iso_for_serial ISO OUT
    local iso=$1 out=$2 work
    command -v xorriso >/dev/null || return 1
    [[ -s $out ]] && return 0

    work=$(mktemp -d)
    bsdtar -xOf "$iso" EFI/BOOT/grub.cfg      > "$work/grub.cfg"     2>/dev/null || { rm -rf "$work"; return 1; }
    bsdtar -xOf "$iso" isolinux/isolinux.cfg  > "$work/isolinux.cfg" 2>/dev/null || { rm -rf "$work"; return 1; }

    # GRUB: put the bootloader itself on serial (so a failure in GRUB is
    # visible, and so input works at all), shorten the countdown, and add a
    # serial console to every kernel line. Entries in the "Serial console"
    # submenu already carry it; a duplicate is harmless.
    {
        printf 'serial --unit=0 --speed=115200\n'
        printf 'terminal_input serial console\n'
        printf 'terminal_output serial console\n'
        sed -e 's/^\([[:space:]]*set timeout=\).*/\13/' \
            -e '/^[[:space:]]*linux /{/console=ttyS0/!s/$/ console=ttyS0,115200n8/}' \
            "$work/grub.cfg"
    } > "$work/grub.cfg.new"

    # isolinux already opens with `SERIAL 0 115200`; it just needs the kernel
    # command line to match.
    sed -e '/^[[:space:]]*APPEND /{/console=ttyS0/!s/$/ console=ttyS0,115200n8/}' \
        -e 's/^TIMEOUT .*/TIMEOUT 30/' \
        "$work/isolinux.cfg" > "$work/isolinux.cfg.new"

    xorriso -indev "$iso" -outdev "$out" \
        -boot_image any replay \
        -map "$work/grub.cfg.new"     /EFI/BOOT/grub.cfg \
        -map "$work/isolinux.cfg.new" /isolinux/isolinux.cfg \
        >/dev/null 2>&1 || { rm -rf "$work" "$out"; return 1; }

    rm -rf "$work"
    [[ -s $out ]]
}

# Everything install-me.sh reads from SCRIPT_DIR, plus the generated
# unique.nix, as an ISO9660 image. hdiutil is stock macOS, so the suite needs
# nothing installed.
build_repo_iso () { # build_repo_iso REPO_ROOT OUT_ISO
    local root=$1 out=$2 stage
    stage=$(mktemp -d)

    cp "$root/install-me.sh" "$root/replace-boot-disk.sh" "$root/add-data-pool.sh" "$stage/"
    cp "$root/configuration.nix" "$root/disk-layout.nix" "$root/zfs-health.nix" "$stage/"
    mkdir -p "$stage/lib"
    cp "$root/lib/common.sh" "$stage/lib/"
    write_test_unique_nix "$stage/unique.nix"

    rm -f "$out"
    hdiutil makehybrid -quiet -iso -joliet -default-volume-name NIXINST \
        -o "$out" "$stage" || { rm -rf "$stage"; return 1; }
    rm -rf "$stage"
    [[ -s $out ]]
}
